<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.meteor.chat</groupId>
        <artifactId>meteor-chat-framework</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>meteor-chat-sensitiveword</artifactId>
    <version>${revision}</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-common-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-rpc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-user-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-mybatis-starter</artifactId>
        </dependency>
    </dependencies>

</project>