<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.meteor.chat</groupId>
    <artifactId>meteorchat</artifactId>
    <packaging>pom</packaging>
    <version>${revision}</version>
    <modules>
        <module>meteor-chat-dependencies</module>
        <module>meteor-chat-framework</module>
        <module>meteor-chat-push</module>
        <module>meteor-chat-user</module>
        <module>meteor-chat-room</module>
        <module>meteor-chat-msg</module>
        <module>meteor-chat-gateway</module>
    </modules>

    <properties>
        <revision>1.0-SNAPSHOT</revision>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <skipTests>true</skipTests>
        <docker.host>http://192.168.3.101:2375</docker.host>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-dependencies</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>