<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.meteor.chat</groupId>
    <artifactId>meteor-chat-dependencies</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-boot.version>2.6.7</spring-boot.version>
        <spring-cloud.version>2021.0.3</spring-cloud.version>
        <spring-cloud.alibaba.version>2021.0.4.0</spring-cloud.alibaba.version>
        <hutool.version>5.8.18</hutool.version>
        <springfox-swagger.version>3.0.0</springfox-swagger.version>
        <swagger-models.version>1.6.0</swagger-models.version>
        <mybatis-plus-generator.version>3.4.1</mybatis-plus-generator.version>
        <mybatis.version>3.5.10</mybatis.version>
        <mysql-connector.version>8.0.29</mysql-connector.version>
        <spring-data-commons.version>2.7.5</spring-data-commons.version>
        <jwt.version>3.19.0</jwt.version>
        <logstash-logback.version>7.2</logstash-logback.version>
        <minio.version>8.4.5</minio.version>
        <jaxb-api.version>2.3.1</jaxb-api.version>
        <lombok.version>1.18.10</lombok.version>
        <netty-all.version>4.1.76.Final</netty-all.version>
        <weixin-java-mp.version>4.4.0</weixin-java-mp.version>
        <mybatis-plus-boot-starter.version>3.4.0</mybatis-plus-boot-starter.version>
        <jsoup.version>1.15.3</jsoup.version>
        <knife4j.version>4.4.0</knife4j.version>
        <okhttp3.version>4.8.1</okhttp3.version>
        <redisson-spring-boot-starter.version>3.17.1</redisson-spring-boot-starter.version>
        <revision>1.0-SNAPSHOT</revision>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-common-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-oss-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-cache-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-transaction</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-mq-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-web-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-frequency-control</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-rpc</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-redis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-mybatis-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-gateway</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-room-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-room-system</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-msg-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-msg-system</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-server</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-user-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-user-system</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-push-common</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-push-server</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.meteor.chat</groupId>
                <artifactId>meteor-chat-sensitiveword</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi2-spring-boot-starter</artifactId>
                <version>${knife4j.version}</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>${okhttp3.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jsoup</groupId>
                <artifactId>jsoup</artifactId>
                <version>${jsoup.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>${mybatis-plus-boot-starter.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.binarywang</groupId>
                <artifactId>weixin-java-mp</artifactId>
                <version>${weixin-java-mp.version}</version>
            </dependency>
            <!-- netty -->
            <!-- 统一依赖管理 -->
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>${netty-all.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud.alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>
            <!-- MyBatis-->
            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis</artifactId>
                <version>${mybatis.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-generator</artifactId>
                <version>${mybatis-plus-generator.version}</version>
            </dependency>
            <!--Mysql数据库驱动-->
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>${mysql-connector.version}</version>
            </dependency>
            <!--JWT(Json Web Token)登录支持-->
            <dependency>
                <groupId>com.auth0</groupId>
                <artifactId>java-jwt</artifactId>
                <version>${jwt.version}</version>
            </dependency>
            <!-- 阿里云OSS -->
            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>${minio.version}</version>
            </dependency>
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>${redisson-spring-boot-starter.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>