version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: XTso0LLXJfmSxEec3sot
      MINIO_SECRET_KEY: iwbTChAYtLG9guHLvHcuzF4cJaE9AR0qXl2NRFzg
    volumes:
      - minio_data:/data
    command: server /data --console-address :9001
    restart: unless-stopped

  backend:
    build: .
    container_name: chat-back
    ports:
      - "8000:8000"
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: XTso0LLXJfmSxEec3sot
      MINIO_SECRET_KEY: iwbTChAYtLG9guHLvHcuzF4cJaE9AR0qXl2NRFzg
volumes:
  minio_data:

