logging:
  level:
    org:
      springframework:
        web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
    com.meteor.chat.common.mapper: WARN
push:
  instanceId: "01"
spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: meteor-chat-push-server
  main:
    #    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Feign 等会存在重复定义的服务
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml # 加载【Nacos】的配置
  cloud:
    nacos:
      server-addr: 192.168.191.131:8848 # Nacos 服务器地址
      username: nacos # Nacos 账号
      password: nacos # Nacos 密码
      discovery: # 【配置中心】配置项
        namespace: dev # 命名空间。这里使用 dev 开发环境
        group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
        metadata:
          version: 1.0.0 # 服务实例的版本号，可用于灰度发布
      config: # 【注册中心】配置项
        namespace: dev # 命名空间。这里使用 dev 开发环境
        group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
  redis:
    # Redis服务器地址
    host: ${mallchat.redis.host}
    # Redis服务器端口号
    port: ${mallchat.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${mallchat.redis.password}
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 18000
  jackson:
    serialization:
      write-dates-as-timestamps: true
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
    virtual-host: /
#    listener: # 消息消费者配置
#      simple:
#        acknowledge-mode: manual # 手动确认模式（默认 auto）
#        prefetch: 1              # 每次预取的消息数量
#        retry:
#          enabled: true          # 是否启用重试
#          max-attempts: 3        # 最大重试次数
#          initial-interval: 2000 # 初始重试间隔（毫秒）
#      template: # 消息生产者配置
#        retry:
#          enabled: true            # 发送消息失败是否重试
#          max-attempts: 3
#          initial-interval: 2000
#      publisher-confirm-type: correlated  # 开启发布确认（Confirm）
#      publisher-return: true       # 开启消息返回机制（Return Listener）
management:
  server:
    port: 18010
server:
  port: 8010
