##################mysql??##################
mallchat.mysql.ip=127.0.0.1
mallchat.mysql.port=3306
mallchat.mysql.db=meteor_chat
mallchat.mysql.username=root
mallchat.mysql.password=root
##################redis??##################
mallchat.redis.host=47.108.134.246
mallchat.redis.port=6379
mallchat.redis.password=redis1234
##################jwt##################
mallchat.jwt.secret=meteor
##################微信公众号信息##################
mallchat.wx.callback=http://meteor.free.idcfengye.com
mallchat.wx.appId=wxec3ebd1059276549
mallchat.wx.secret=a07464c1a06007b8445b4fa3e162c11c
# 接口配置里的Token值
mallchat.wx.token=meteorchat
# 接口配置里的EncodingAESKey值
mallchat.wx.aesKey=
##################OSS??##################
oss.enabled=true
oss.type=minio
oss.endpoint=http://localhost:9000
oss.access-key=XTso0LLXJfmSxEec3sot
oss.secret-key=iwbTChAYtLG9guHLvHcuzF4cJaE9AR0qXl2NRFzg
oss.bucketName=meteorchat
##################RockerMq##################
rocketmq.name-server=192.168.191.131:9876
rocketmq.access-key=root
rocketmq.secret-key=123456
##################gpt??##################
mallchat.chatgpt.use=false
mallchat.chatgpt.uid=10001
mallchat.chatgpt.key=sk-wvWM0xGcxFfsddfsgxixbXK5tHovM
mallchat.chatgpt.proxyUrl=https://123.cc
mallchat.chatglm2.use=false
mallchat.chatglm2.url=http://v32134.cc
mallchat.chatglm2.uid=10002
