#todo 记得把这些配置信息补充了
##################mysql配置##################
mallchat.mysql.ip=47.108.134.246
mallchat.mysql.port=3306
mallchat.mysql.db=meteor_chat
mallchat.mysql.username=chat
mallchat.mysql.password=chat
##################redis配置##################
mallchat.redis.host=47.108.134.246
mallchat.redis.port=6379
mallchat.redis.password=redis1234
##################jwt##################
mallchat.jwt.secret=meteor
##################微信公众号信息##################
mallchat.wx.callback=http://47.108.134.246:8000
mallchat.wx.appId=wxec3ebd1059276549
mallchat.wx.secret=a07464c1a06007b8445b4fa3e162c11c
# 接口配置里的Token值
mallchat.wx.token=meteor
# 接口配置里的EncodingAESKey值
mallchat.wx.aesKey=
##################OSS配置##################
oss.enabled=true
oss.type=minio
oss.endpoint=http://47.108.134.246:9000
oss.access-key=D7D8yzGdNZ9UukX2OUpA
oss.secret-key=Bn5SPoU9hRWVH16dtI2RgG6RteFJFjaAtOmMuNtf
oss.bucketName=meteorchat
##################rocketmq##################
rocketmq.name-server=47.108.134.246:9876
rocketmq.access-key=root
rocketmq.secret-key=123456
##################gpt配置##################
mallchat.chatgpt.use=false
mallchat.chatgpt.uid=10001
mallchat.chatgpt.key=sk-wvWM0xGcxFfsddfsgxixbXK5tHovM
mallchat.chatgpt.proxyUrl=https://123.cc
mallchat.chatglm2.use=false
mallchat.chatglm2.url=http://v32134.cc
mallchat.chatglm2.uid=10002
mallchat.chatglm2.context=3
