<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.meteor.chat</groupId>
        <artifactId>meteor-chat-user</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>meteor-chat-user-system</artifactId>
    <version>${revision}</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-common-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-mybatis-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-user-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-push-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-web-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-cache-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-oss-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-sensitiveword</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-room-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-msg-api</artifactId>
        </dependency>
        <!-- 负载均衡 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>

        <!-- Registry 注册中心相关 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- Config 配置中心相关 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <!-- RPC 远程调用-->
        <dependency>
            <groupId>com.meteor.chat</groupId>
            <artifactId>meteor-chat-rpc</artifactId>
        </dependency>
    </dependencies>

</project>